[package]
name = "my-git"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
flate2 = "1.1.2"
sha1 = "0.10.6"

[dev-dependencies]
tempfile = "3.20.0"
mockall = "0.13.1"